[alias] # command aliases
b = "build"
lb = "lbuild"
br = "build --release"
lbr = "lbuild --release"
c = "check"
lc = "lcheck"
t = "test"
r = "run"
lr = "lrun"
rr = "run --release"
lrr = "lrun --release"

[build]
# target-dir = "misc/.target"         # path of where to place all generated artifacts
incremental = true # whether or not to enable incremental compilation

[unstable]
# threads = 8
# profile-rustflags = true
#
[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
# rustflags = [
#   "-C",
#   "target-cpu=native",
#   "-C",
#   "link-arg=--ld-path=/usr/bin/mold",
#   "-Z",
#   "threads=8",
# ]
rustflags = [
  "-C",
  "target-cpu=native",
  "-C",
  "link-arg=--ld-path=/usr/bin/mold",
]
# rustflags = ["-C", "target-cpu=native", "-Z", "threads=8"]
# rustflags = ["-C", "target-cpu=native"]

[net]
git-fetch-with-cli = true

[registries.crates-io]
protocol = "sparse"

[profile.dev]
opt-level = 0
lto = false

[profile.release]
opt-level = 3
lto = true

[future-incompat-report]
frequency = 'always' # when to display a notification about a future incompat report

[cargo-new]
vcs = "git" # VCS to use ('git', 'hg', 'pijul', 'fossil', 'none')

[term]
quiet = false          # whether cargo output is quiet
verbose = false        # whether cargo provides verbose output
color = 'auto'         # whether cargo colorizes output
progress.when = 'auto' # whether cargo shows progress bar
