#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

. ~/.config/bspwm/scripts/autostart.sh &

bspc monitor DP-0 -d I II III IV V
bspc monitor DP-2 -d VI VII VII IX X
bspc config border_width         3
bspc config window_gap          6

bspc config border_radius 4
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer	false

export color1="#595959"
export color2="#7de0a8"
export color3="#e07db5"
export color4="#357aa0"
export color5="#a87de0"
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color5"
bspc config presel_feedback_color "$color3"
bspc rule -a Zoom state=unmanaged

bspc rule -a plasmashell manage=off
bspc rule -a krunner state=floating border=off
bspc rule -a Zathura state=floating
bspc rule -a GLava state=floating manage=off


#bspc config external_rules_command ~/.config/bspwm/scripts/external_rules.sh
setxkbmap -option 'grp:win_space_toggle' -layout us,ua,ru

bspc rule -a pavucontrol state=floating
#picom -f &
pkill feh
feh --bg-fill /home/roman/Downloads/Wallpapers/WALLPAPER-LOWER-4k-lossless.png &
#$HOME/.config/polybar/launch.sh &

#xinput set-prop 'Glorious Model D' 'libinput Accel Speed' -.7 &
#xsetroot -cursor_name left_ptr &
#dunst &

python $HOME/.config/bspwm/scripts/span_monitors.py &
