#!/bin/bash

# wm independent hotkeys

# terminal emulator
alt + {shift,_} + ctrl + t
	{kitty &, st &}
super + Return
	sh -c "st &"
# program launcher
alt + space
	bash -c "python .config/sxhkd/change_layout.py us; ~/.config/rofi/launcher/launcher.sh " &
{_,super} + Print
	bash -c '$(cd {/tmp,~/Screenshots} && name=$(date +"%H:%M:%S_%d_%B").png && maim -m 9 -u -s -b 2 -c 0.75,0.8,0.96,1 $name && xclip -selection clipboard -target image/png -i $name &) &'

# file manager
super + e
    thunar &
# app hotkeys
super + {_,shift} + c
	sh {~/.config/sxhkd/NeoVim.sh, ~/.config/sxhkd/FirefoxDevEd.sh &}
# switching
alt + {_, shift} + Tab
	bspc node -f {next,last}.local.window
super + {_,shift} + Tab
	{bspc monitor -f next, bspc node -m next && bspc monitor -f next}

# color picker
super + n
    xcolor -f HEX! --scale 4 -s clipboard

# language switching
super + space
	python $HOME/.config/sxhkd/change_layout.py & xdo lower -N "Polybar" &
super + r
	bspc node @parent -R 90 &

# make sxhkd reload its configuration files:
super + Escape
	pkill -USR1 -x sxhkd
# Close one/all windows of an app
ctrl + shift + {_,super + }q
    bspc node -{c,k}
ctrl + super + alt + l
	python $HOME/.config/sxhkd/change_layout.py us && $HOME/.config/sxhkd/lock.sh
#
# bspwm hotkeys
#
super + alt + {plus, equal}
	bspc config window_gap (expr (bspc config window_gap) + 2)

super + alt + minus
	bspc config window_gap (expr (bspc config window_gap) - 2)

# quit/restart bspwm
super + alt + {q,r}
	bspc {quit,wm -r}


# alternate between the tiled and monocle layout
super + m
	bspc desktop -l next

# Send the currently focused node to the newest preselection
super + y
	bspc node focused -n newest.!automatic.local

# float and resize to mouse selection
super + g
	bash ~/.config/sxhkd/mover.sh
#
# state/flags
#

# set the window state
super + {t,shift + t,s,f}
	bspc node -t {tiled,pseudo_tiled,floating,fullscreen}

# set the node flags
super + ctrl + {m,x,y,z}
	bspc node -g {marked,locked,sticky,private}

#
# focus/swap
#

# focus the node in the given direction
super + {_,shift + }{h,j,k,l}
	bspc node -{f,s} {west,south,north,east}

# focus the node for the given path jump
super + {p,b,comma,period}
	bspc node -f @{parent,brother,first,second}

# focus the next/previous window in the current desktop

# focus the next/previous desktop in the current monitor
super + {backslash, bracketleft}
	bspc desktop -f {next,prev}.local

# focus the last node/desktop

# focus the older or newer node in the focus history
super + {o,i}
	bspc wm -h off; \
	bspc node {older,newer} -f; \
	bspc wm -h on

# focus or send to the given desktop
super + {_,shift + }{1-9,0}
	bspc {desktop -f,node -d} '^{1-9,10}' --follow

#
# preselect
#

# preselect the direction
super + ctrl + {h,j,k,l}
	bspc node -p {west,south,north,east}

# preselect the ratio
super + ctrl + {1-9}
	bspc node -o 0.{1-9}

# cancel the preselection for the focused node
super + ctrl + space
	bspc node -p cancel

# cancel the preselection for the focused desktop
super + ctrl + shift + space
	bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel

#
# move/resize
#

# expand a window by moving one of its side outward
super + alt + {h,j,k,l}
	bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# contract a window by moving one of its side inward
super + alt + shift + {h,j,k,l}
	bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

# move a floating window
super + {Left,Down,Up,Right}
	bspc node -v {-40 0,0 40,0 -40,40 0}
