--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/roman/stuff/wallpaper.png"

-- Special
background="#181818"
foreground="#b9b9b9"
cursor="#B9B9B9"

-- Colors
color0="#252525"
color1="#ED4A46"
color2="#70B433"
color3="#DBB32D"
color4="#368AEB"
color5="#EB6EB7"
color6="#3FC5B7"
color7="#777777"
color8="#3B3B3B"
color9="#FF5E56"
color10="#83C746"
color11="#EFC541"
color12="#4F9CFE"
color13="#FF81CA"
color14="#56D8C9"
color15="#DEDEDE"
