# Shell variables
# Generated by 'wal'
wallpaper="/home/roman/stuff/cyberpunk-challenger-2560×1440.jpg"

# Special
background='#0C1A1D'
foreground='#c2abe0'
cursor='#c2abe0'

# Colors
color0='#0C1A1D'
color1='#3D445F'
color2='#A15367'
color3='#2E3893'
color4='#5F4EA7'
color5='#5347A9'
color6='#955EAD'
color7='#c2abe0'
color8='#87779c'
color9='#3D445F'
color10='#A15367'
color11='#2E3893'
color12='#5F4EA7'
color13='#5347A9'
color14='#955EAD'
color15='#c2abe0'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
