--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/roman/stuff/wallpaper.png"

-- Special
background="#11121D"
foreground="#c0caf5"
cursor="#f7768e"

-- Colors
color0="#11121D"
color1="#f7768e"
color2="#9ece6a"
color3="#e0af68"
color4="#7aa2f7"
color5="#bb9af7"
color6="#7dcfff"
color7="#a9b1d6"
color8="#414868"
color9="#f7768e"
color10="#9ece6a"
color11="#e0af68"
color12="#7aa2f7"
color13="#bb9af7"
color14="#7dcfff"
color15="#c0caf5"
