--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/roman/stuff/cyberpunk-challenger-2560×1440.jpg"

-- Special
background="#0C1A1D"
foreground="#c2abe0"
cursor="#c2abe0"

-- Colors
color0="#0C1A1D"
color1="#3D445F"
color2="#A15367"
color3="#2E3893"
color4="#5F4EA7"
color5="#5347A9"
color6="#955EAD"
color7="#c2abe0"
color8="#87779c"
color9="#3D445F"
color10="#A15367"
color11="#2E3893"
color12="#5F4EA7"
color13="#5347A9"
color14="#955EAD"
color15="#c2abe0"
