#!/bin/sh
# Shell variables
# Generated by 'wal'
wallpaper="/home/roman/stuff/wallpaper.png"

# Special
export background='#11121D'
export foreground='#c0caf5'
export cursor='#f7768e'

# Colors
export color0='#11121D'
export color1='#f7768e'
export color2='#9ece6a'
export color3='#e0af68'
export color4='#7aa2f7'
export color5='#bb9af7'
export color6='#7dcfff'
export color7='#a9b1d6'
export color8='#414868'
export color9='#f7768e'
export color10='#9ece6a'
export color11='#e0af68'
export color12='#7aa2f7'
export color13='#bb9af7'
export color14='#7dcfff'
export color15='#c0caf5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
# export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
