#!/bin/sh

sxhkd &

bash "${HOME}/.config/bspwm/scripts/autostart.sh" &
xrdb -override "${HOME}/.Xresources"

bspc config ignore_ewmh_struts true
bspc config border_width 2
bspc config window_gap 6

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer false
bspc config top_padding 40
bspc config remove_unplugged_monitors true

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"

python $HOME/.config/bspwm/scripts/span_monitors.py &

bspc rule -a Zathura state=tiled
bspc rule -a "zoom " state=floating border=off
bspc rule -a GLava state=floating manage=off
bspc rule -a pavucontrol state=floating
# Splash Float
#bspc rule -a SPLASH:SPLASH border=off layer=below state=floating sticky=on follow=on locked=on manage=on
#pkill splash
#splash fidget --bg -a -p 2120 1080 440 360 &

xsetroot -cursor_name left_ptr
# feh --bg-fill ~/.config/bspwm/wallpaper.png &

#bspc config external_rules_command ~/.config/bspwm/scripts/external_rules.sh
setxkbmap -option caps:none -layout us &

#$HOME/.config/polybar/launch.sh &

#xinput set-prop 'Glorious Model D' 'libinput Accel Speed' -.7 &
#xsetroot -cursor_name left_ptr &
#dunst &
