#!/bin/sh

killall sxhkd
sxhkd &

sh ~/.config/bspwm/scripts/autostart.sh &

bspc monitor DP-0 -d I II III IV V
bspc monitor DP-2 -d VI VII VII IX X
bspc config border_width 2
bspc config window_gap 10

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer false
bspc config top_padding 43
bspc config remove_unplugged_monitors true

export color1="#1A1B26"
export color2="#414868"
export color3="#7E84A0"
export color4="#357aa0"
export color5="#C0CAF5"
bspc config normal_border_color "$color2"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color5"
bspc config presel_feedback_color "$color2"

bspc rule -a Zathura state=floating
bspc rule -a "zoom " state=floating border=off
bspc rule -a GLava state=floating manage=off
bspc rule -a pavucontrol state=floating
# Splash Float
#bspc rule -a SPLASH:SPLASH border=off layer=below state=floating sticky=on follow=on locked=on manage=on
#pkill splash
#splash fidget --bg -a -p 2120 1080 440 360 &

xsetroot -cursor_name left_ptr
feh --bg-fill ~/.config/bspwm/wallpaper.png &

#bspc config external_rules_command ~/.config/bspwm/scripts/external_rules.sh
setxkbmap -option caps:none -layout us

#picom -f &
#$HOME/.config/polybar/launch.sh &

#xinput set-prop 'Glorious Model D' 'libinput Accel Speed' -.7 &
#xsetroot -cursor_name left_ptr &
#dunst &

python $HOME/.config/bspwm/scripts/span_monitors.py &
gamemoded &
